### ISSUE TITLE
哥们，有博客地址吗

### ISSUE THREAD

**Issue by bugparty** [HamsterReserved/blog_posts#1]

**Comment by updateing** [comment]
这里就是了 [doge]

**Comment by bugparty** [comment]
给我一种秘密基地的感觉，coding.net可以免费托管php

**Comment by updateing** [comment]
曾经用 Hexo 做过（这里的文件结构可以直接拿进 Hexo 生成静态文件），然后太懒了又觉得 GitHub 自带 Markdown 渲染也不差，就直接用 GitHub 好了 😂

**Comment by bugparty** [comment]
额，看你想公开，还是悄悄的放着。。。

2017-12-28 17:34 GMT+08:00 Hamster Tian <notifications@github.com>:

**Comment by updateing** [comment]
公不公开似乎与内容放在哪里没有太大联系……

**Comment by bugparty** [comment]
搜索引擎搜不到

2017-12-29 17:53 GMT+08:00 Hamster Tian <notifications@github.com>:

**Comment by updateing** [comment]
GitHub 反而更容易被搜到……
